version: '3.9'

services:
  kanalservis_app: 
    container_name: kanalservis_app
    image: kanalservis_app
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db

  db:
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    image: postgres:14.3-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata: {}
